const gymEquipments = [
  {
    id: 1,
    name: 'Treadmill',
    description: 'Indoor running and walking cardio machine.',
    image: 'treadmill',
  },
  {
    id: 2,
    name: 'Stationary Bike',
    description: 'Low-impact cycling cardio equipment.',
    image: 'stationary_bike',
  },
  {
    id: 3,
    name: 'Elliptical Trainer',
    description: 'Full-body low-impact cardio machine.',
    image: 'elliptical_trainer',
  },
  {
    id: 4,
    name: 'Rowing Machine',
    description: 'Full-body strength and cardio workout machine.',
    image: 'rowing_machine',
  },
  {
    id: 5,
    name: 'Stair Climber',
    description: 'Simulates stair climbing for leg endurance.',
    image: 'stair_climber',
  },
  {
    id: 6,
    name: 'Spin Bike',
    description: 'High-intensity indoor cycling bike.',
    image: 'spin_bike',
  },

  {
    id: 7,
    name: 'Dumbbells',
    description: 'Handheld weights for strength training.',
    image: 'dumbbells',
  },
  {
    id: 8,
    name: 'Barbell',
    description: 'Long bar used for compound lifts.',
    image: 'barbell',
  },
  {
    id: 9,
    name: 'EZ Curl Bar',
    description: 'Curved bar for comfortable arm workouts.',
    image: 'ez_curl_bar',
  },
  {
    id: 10,
    name: 'Weight Plates',
    description: 'Plates added to barbells or machines.',
    image: 'weight_plates',
  },
  {
    id: 11,
    name: 'Kettlebell',
    description: 'Used for strength and functional training.',
    image: 'kettlebell',
  },
  {
    id: 12,
    name: 'Medicine Ball',
    description: 'Weighted ball for core and explosive training.',
    image: 'medicine_ball',
  },

  {
    id: 13,
    name: 'Bench Press',
    description: 'Flat bench for chest press exercises.',
    image: 'bench_press',
  },
  {
    id: 14,
    name: 'Incline Bench',
    description: 'Adjustable bench for upper chest workouts.',
    image: 'incline_bench',
  },
  {
    id: 15,
    name: 'Decline Bench',
    description: 'Bench angled downward for lower chest exercises.',
    image: 'decline_bench',
  },
  {
    id: 16,
    name: 'Adjustable Bench',
    description: 'Multi-position bench for various exercises.',
    image: 'adjustable_bench',
  },

  {
    id: 17,
    name: 'Smith Machine',
    description: 'Guided barbell system for safe lifting.',
    image: 'smith_machine',
  },
  {
    id: 18,
    name: 'Cable Machine',
    description: 'Pulley-based machine for full-body workouts.',
    image: 'cable_machine',
  },
  {
    id: 19,
    name: 'Chest Press Machine',
    description: 'Machine targeting chest and triceps.',
    image: 'chest_press_machine',
  },
  {
    id: 20,
    name: 'Pec Deck Machine',
    description: 'Isolates chest muscles.',
    image: 'pec_deck_machine',
  },
  {
    id: 21,
    name: 'Shoulder Press Machine',
    description: 'Targets shoulder muscles.',
    image: 'shoulder_press_machine',
  },
  {
    id: 22,
    name: 'Lat Pulldown Machine',
    description: 'Works upper back and lats.',
    image: 'lat_pulldown_machine',
  },
  {
    id: 23,
    name: 'Seated Row Machine',
    description: 'Strengthens middle back.',
    image: 'seated_row_machine',
  },

  {
    id: 24,
    name: 'Leg Press Machine',
    description: 'Targets quads, glutes, and hamstrings.',
    image: 'leg_press_machine',
  },
  {
    id: 25,
    name: 'Leg Extension Machine',
    description: 'Isolates quadriceps.',
    image: 'leg_extension_machine',
  },
  {
    id: 26,
    name: 'Leg Curl Machine',
    description: 'Targets hamstrings.',
    image: 'leg_curl_machine',
  },
  {
    id: 27,
    name: 'Hack Squat Machine',
    description: 'Lower body strength training machine.',
    image: 'hack_squat_machine',
  },
  {
    id: 28,
    name: 'Calf Raise Machine',
    description: 'Builds calf muscles.',
    image: 'calf_raise_machine',
  },
  {
    id: 29,
    name: 'Hip Abductor Machine',
    description: 'Works outer thigh muscles.',
    image: 'hip_abductor_machine',
  },
  {
    id: 30,
    name: 'Hip Adductor Machine',
    description: 'Works inner thigh muscles.',
    image: 'hip_adductor_machine',
  },

  {
    id: 31,
    name: 'Pull-up Bar',
    description: 'Bodyweight back and arm training.',
    image: 'pullup_bar',
  },
  {
    id: 32,
    name: 'Dip Station',
    description: 'Targets chest and triceps.',
    image: 'dip_station',
  },
  {
    id: 33,
    name: 'Power Rack',
    description: 'Frame for heavy barbell lifts.',
    image: 'power_rack',
  },
  {
    id: 34,
    name: 'Squat Rack',
    description: 'Supports barbell squats.',
    image: 'squat_rack',
  },
  {
    id: 35,
    name: 'Deadlift Platform',
    description: 'Platform for safe deadlifting.',
    image: 'deadlift_platform',
  },

  {
    id: 36,
    name: 'Battle Ropes',
    description: 'High-intensity functional training ropes.',
    image: 'battle_ropes',
  },
  {
    id: 37,
    name: 'Resistance Bands',
    description: 'Elastic bands for strength and rehab.',
    image: 'resistance_bands',
  },
  {
    id: 38,
    name: 'TRX Suspension Trainer',
    description: 'Bodyweight suspension training system.',
    image: 'trx_trainer',
  },
  {
    id: 39,
    name: 'Stability Ball',
    description: 'Improves balance and core strength.',
    image: 'stability_ball',
  },
  {
    id: 40,
    name: 'BOSU Ball',
    description: 'Half stability ball for balance exercises.',
    image: 'bosu_ball',
  },
  {
    id: 41,
    name: 'Ab Roller',
    description: 'Strengthens abdominal muscles.',
    image: 'ab_roller',
  },
  {
    id: 42,
    name: 'Roman Chair',
    description: 'Targets lower back and core.',
    image: 'roman_chair',
  },

  {
    id: 43,
    name: 'Foam Roller',
    description: 'Used for muscle recovery and stretching.',
    image: 'foam_roller',
  },
  {
    id: 44,
    name: 'Punching Bag',
    description: 'Used for boxing and cardio training.',
    image: 'punching_bag',
  },
  {
    id: 45,
    name: 'Speed Bag',
    description: 'Improves hand speed and coordination.',
    image: 'speed_bag',
  },
  {
    id: 46,
    name: 'Jump Rope',
    description: 'Simple tool for cardio and agility.',
    image: 'jump_rope',
  },
  {
    id: 47,
    name: 'Weight Sled',
    description: 'Used for strength and conditioning drills.',
    image: 'weight_sled',
  },
  {
    id: 48,
    name: 'Farmer Walk Handles',
    description: 'Used for grip and core strength.',
    image: 'farmer_walk_handles',
  },
  {
    id: 49,
    name: 'Grip Strengthener',
    description: 'Improves hand and forearm strength.',
    image: 'grip_strengthener',
  },
  {
    id: 50,
    name: 'Glute Bridge Machine',
    description: 'Targets glute muscles.',
    image: 'glute_bridge_machine',
  },
  {
    id: 51,
    name: 'Reverse Hyper Machine',
    description: 'Strengthens lower back and glutes.',
    image: 'reverse_hyper_machine',
  },
  {
    id: 52,
    name: 'Sissy Squat Machine',
    description: 'Isolates quadriceps muscles.',
    image: 'sissy_squat_machine',
  },
  {
    id: 53,
    name: 'Cable Crossover Machine',
    description: 'Used for chest fly exercises.',
    image: 'cable_crossover_machine',
  },
  {
    id: 54,
    name: 'Arm Blaster',
    description: 'Helps isolate biceps during curls.',
    image: 'arm_blaster',
  },
  {
    id: 55,
    name: 'Wrist Roller',
    description: 'Builds forearm strength.',
    image: 'wrist_roller',
  },
  {
    id: 56,
    name: 'Ankle Weights',
    description: 'Adds resistance to leg exercises.',
    image: 'ankle_weights',
  },
  {
    id: 57,
    name: 'Weighted Vest',
    description: 'Adds extra resistance to bodyweight workouts.',
    image: 'weighted_vest',
  },
  {
    id: 58,
    name: 'Core Sliders',
    description: 'Used for core and stability training.',
    image: 'core_sliders',
  },
  {
    id: 59,
    name: 'Parallettes',
    description: 'Used for calisthenics exercises.',
    image: 'parallettes',
  },
  {
    id: 60,
    name: 'Gym Rings',
    description: 'Suspension rings for advanced bodyweight training.',
    image: 'gym_rings',
  },
];
